sudo: false
language: node_js
node_js:
- '8'

install:
- yarn
- yarn global add hexo-cli

script:
- hexo g
- hexo d
- rm -rf ~/.ssh

branches:
  only:
  - master

deploy:
  provider: firebase
  skip_cleanup: true
  token: ${FIREBASE_TOKEN}

cache:
  yarn: true
  directories:
  - node_modules

before_install:
- openssl aes-256-cbc -K $encrypted_493ca07042a9_key -iv $encrypted_493ca07042a9_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'raincal'
- git config --global user.email 'cyj228@vip.qq.com'
